/**
 * Which assets may be published, and which may not.
 *
 * The library is two libraries wearing one coat. Most of it is The Weather
 * Channel's: narrator recordings, production music, broadcast art, licensed
 * typefaces. Some of it is ours or freely licensed: generated gradients,
 * recreated icons, open fonts, synthesised tones.
 *
 * Those two have different rules and always did. The desktop build is a thing
 * you run on your own machine from material you obtained yourself. The web
 * build at weather.codyhurst.com is publication — it hands the bytes to
 * anyone who loads the page, which is redistribution however the folder is
 * named. Keeping both in one undifferentiated `assets/` meant the only thing
 * standing between the two was remembering, every time, which files were
 * which. That is not a control.
 *
 * So every asset carries a tier:
 *
 *   real   Rights-encumbered. TWC recordings, production music, broadcast
 *          art, commercial typefaces. Desktop only. NEVER reaches the web
 *          build, and the packaging step fails rather than let one through.
 *
 *   clean  Safe to publish. Recreated or generated art, open-licensed fonts,
 *          synthesised audio, public-domain data. This is what ships to the
 *          site.
 *
 * Classification is by rule rather than by a 13,000-line manifest, because a
 * manifest goes stale the moment somebody adds a file and a rule does not.
 * The cost is that a rule can be wrong, so the default for anything
 * unmatched is `real` — the failure mode of mislabelling a clean asset is a
 * missing image, and the failure mode of mislabelling an encumbered one is a
 * takedown. Those are not comparable, so the tie goes to caution.
 *
 * Adding a genuinely publishable asset means adding it to CLEAN_RULES with a
 * note on why it is safe. "I think it's fine" is not a note.
 */

/** @typedef {"real" | "clean"} Tier */

/**
 * Paths that are safe to publish, most specific first.
 *
 * `test` is matched against the asset path relative to `assets/`, always with
 * forward slashes.
 */
export const CLEAN_RULES = [
  {
    test: /^fonts\/(open|inter|noto|dejavu|liberation|roboto)\//i,
    why: "Open-licensed typefaces (SIL OFL / Apache). Redistribution is permitted by their licences.",
  },
  {
    test: /^backgrounds\/generated\//,
    why: "Gradients and plates generated by our own build scripts. No TWC art involved.",
  },
  {
    test: /^icons\/recreated\//,
    why: "Condition icons redrawn from scratch to match the originals' silhouette and palette without copying the artwork.",
  },
  {
    test: /^sfx\/synth\//,
    why: "Alert tones synthesised at runtime specifications (NWS attention signal is a published standard, not a recording).",
  },
  {
    test: /^data\//,
    why: "Station lists, city tables and coordinates. Facts, from NWS and FAA public sources.",
  },
  {
    test: /^logos\/awc\//,
    why: "This application's own branding.",
  },
];

/**
 * Encumbered paths, called out explicitly rather than left to the default.
 *
 * These exist so the classifier can say WHY something is `real` instead of
 * shrugging and saying "nothing matched". A reviewer reading the report
 * should be able to see the reasoning, not just the verdict.
 */
export const REAL_RULES = [
  { test: /^narration\//, why: "TWC narrator recordings (Allen Jackson, Jim Cantore, Amy Bargeron, Dan Chandler)." },
  { test: /^music\//, why: "TWC production music — Trammell Starks, in-house library, Man Made Music." },
  { test: /^backgrounds\//, why: "Broadcast background art captured from TWC hardware." },
  { test: /^themes\//, why: "Per-machine broadcast art and chrome." },
  { test: /^icons\//, why: "TWC condition icon artwork." },
  { test: /^fonts\//, why: "Commercial typefaces (Interstate, Frutiger, Helvetica, Akzidenz-Grotesk) licensed to TWC, not to us." },
  { test: /^sounds?\//, why: "Recorded stingers and mnemonics." },
  { test: /^sfx\//, why: "Recorded effects." },
  { test: /^inbox\//, why: "Unsorted intake. Unclassified material is encumbered until reviewed." },
];

/**
 * Classify one asset path (relative to `assets/`, forward slashes).
 * @returns {{ tier: Tier, why: string, rule: string }}
 */
export function classify(relPath) {
  const p = relPath.replace(/\\/g, "/").replace(/^\.\//, "");
  for (const rule of CLEAN_RULES) {
    if (rule.test.test(p)) return { tier: "clean", why: rule.why, rule: String(rule.test) };
  }
  for (const rule of REAL_RULES) {
    if (rule.test.test(p)) return { tier: "real", why: rule.why, rule: String(rule.test) };
  }
  return {
    tier: "real",
    why: "Unclassified. The default is `real` on purpose — an unrecognised asset is assumed encumbered until somebody says otherwise in scripts/asset-tiers.mjs.",
    rule: "(default)",
  };
}

/** True if this asset may be published to the web build. */
export function isPublishable(relPath) {
  return classify(relPath).tier === "clean";
}
