/**
 * Generates the two reference documents for sourcing work:
 *
 *   docs/clip-wishlist.md — the exact phrases missing, per narrator and
 *                           scene. This is the shopping list for aircheck
 *                           hunting; nothing else in the repo says plainly
 *                           "these words, in this voice, are what we need".
 *   docs/asset-gaps.md    — per-machine art, layout and audio gaps, from the
 *                           `gaps` field on each device profile.
 *
 * Both are generated so they cannot drift from the code. Re-run after
 * changing a device profile or wiring a new clip:
 *
 *   npm run device:report
 */
import { build } from "esbuild";
import * as fs from "node:fs";
import * as fsp from "node:fs/promises";
import * as path from "node:path";
import { pathToFileURL, fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(ROOT, ".device-report");
fs.rmSync(outDir, { recursive: true, force: true });

await build({
  stdin: {
    contents: `
      export { DEVICES, getDevice, deviceSceneOrder } from "./src/devices";
      export { pickSceneIntro, NARRATORS, getNarrator } from "./src/audio/manifests/narratorSchema";
      export { setProductEra, segmentLabel } from "./src/audio/manifests/sceneSegments";
      export { getNarratorClips, setClipReferenceTable } from "./src/audio/data/clipReferenceTable";
    `,
    resolveDir: ROOT, sourcefile: "report.ts", loader: "ts"
  },
  bundle: true, format: "esm", platform: "node", target: "node18",
  outfile: path.join(outDir, "m.mjs"), logLevel: "silent"
});
const m = await import(pathToFileURL(path.join(outDir, "m.mjs")).toString());

// Tooling wants the transcription text, so install the FULL table rather than
// the compact runtime index the app fetches.
{
  const full = JSON.parse(fs.readFileSync(path.join(ROOT, "src/audio/data/clipReferenceTable.json"), "utf8"));
  m.setClipReferenceTable(full);
}

const NARRATORS = m.NARRATORS.filter((n) => n.id !== "silent");
const stamp = new Date().toISOString().slice(0, 10);

// ─────────────────────────── clip wishlist ───────────────────────────

/** Phrase we would want, per product. Written as the narrator would say it. */
const WANTED_PHRASE = {
  almanac:      ['"Your Almanac"', '"Sunrise and sunset for your area"'],
  precip:       ['"Your precipitation outlook"', '"Rainfall totals for your area"'],
  airport:      ['"Airport delays"', '"Delays at your local airport"'],
  travel:       ['"Your travel cities forecast"', '"Forecast for cities nationwide"'],
  traffic:      ['"Traffic for your area"'],
  weekend:      ['"Your weekend forecast"', '"Heading into the weekend"'],
  radar:        ['"Your local Doppler radar"'],
  stormtracker: ['"Storms in your area"'],
  extended:     ['"Your extended forecast"', '"Your 7-day outlook"'],
  detailed:     ['"Your local observations"'],
  feelslike:    ['"What it feels like"'],
  temptrend:    ['"Your temperature trend"'],
  current:      ['"Your current conditions"'],
  hourly:       ['"Your daypart forecast"', '"Your daily planner"'],
  localforecast:['"Your local forecast"', '"Your 36-hour forecast"'],
  overnight:    ['"Your overnight forecast"'],
  alerts:       ['"Is in effect for your area"']
};

const PRODUCTS = Object.keys(WANTED_PHRASE);

m.setProductEra("ws4000-v2");
const missing = [];
for (const product of PRODUCTS) {
  for (const n of NARRATORS) {
    if (m.pickSceneIntro(n.id, product)) continue;
    missing.push({ product, narrator: n.id, label: n.label });
  }
}

const byProduct = new Map();
for (const row of missing) {
  if (!byProduct.has(row.product)) byProduct.set(row.product, []);
  byProduct.get(row.product).push(row);
}

// Which machines actually care — a gap only matters if a device that uses
// that narrator can show that product.
function affectedDevices(product, narratorId) {
  return m.DEVICES
    .filter((d) => d.voice === narratorId)
    .filter((d) => (d.products[product]?.availability ?? "optional") !== "absent")
    .map((d) => d.label);
}

let wishlist = `# Clip wishlist

Generated by \`npm run device:report\` on ${stamp}. Do not edit by hand.

Every entry is a narrator who cannot announce a product the emulator can
show. These are missing **recordings** — the wiring is in place and will pick
them up automatically once the audio exists. Drop a file into the narrator's
library, add it to \`sceneIntros\` in \`src/audio/manifests/narratorSchema.ts\`,
and \`npm run clips:sweep\` will confirm it resolves.

A gap marked "no affected machine" is harmless: no device using that voice
shows that product, so nothing is silent in practice.

`;

for (const [product, rows] of [...byProduct.entries()].sort()) {
  const wanted = WANTED_PHRASE[product] ?? [];
  wishlist += `## ${product}\n\nPhrases wanted: ${wanted.join(" / ")}\n\n`;
  wishlist += `| Narrator | Machines that would use it |\n|---|---|\n`;
  for (const r of rows) {
    const devices = affectedDevices(product, r.narrator);
    wishlist += `| ${r.label} | ${devices.length ? devices.join("; ") : "_no affected machine_" } |\n`;
  }
  wishlist += `\n`;
}

wishlist += `## Library sizes, for context\n\n| Narrator | Clips |\n|---|---|\n`;
for (const n of NARRATORS) {
  wishlist += `| ${n.label} | ${Object.keys(m.getNarratorClips(n.id)).length} |\n`;
}
wishlist += `\nAmy Bargeron's nine clips are the complete set that was ever recorded\nfor her — not a gap to close.\n`;

await fsp.writeFile(path.join(ROOT, "docs/clip-wishlist.md"), wishlist);

// ─────────────────────────── asset gaps ───────────────────────────

let gaps = `# Asset and layout gaps, by machine

Generated by \`npm run device:report\` on ${stamp}. Do not edit by hand —
edit the \`gaps\` field in \`src/devices/profiles/<id>.ts\`.

Each machine is a separate emulation target. This is what stands between the
current rendering and a faithful one.

`;

for (const d of m.DEVICES) {
  const order = m.deviceSceneOrder(d.id);
  const absent = Object.entries(d.products)
    .filter(([, spec]) => spec.availability === "absent")
    .map(([id, spec]) => `\`${id}\`${spec.absentNote ? ` — ${spec.absentNote}` : ""}`);
  const optional = Object.entries(d.products)
    .filter(([, spec]) => spec.availability === "optional")
    .map(([id]) => `\`${id}\``);

  gaps += `## ${d.label}\n\n`;
  gaps += `- **Years:** ${d.years}\n`;
  gaps += `- **Voice:** ${d.voice}\n`;
  gaps += `- **Product era:** ${d.era}\n`;
  gaps += `- **Extended forecast:** ${d.extendedDays}-day\n`;
  gaps += `- **Capabilities:** ${Object.entries(d.capabilities).filter(([, v]) => v).map(([k]) => k).join(", ") || "none"}\n`;
  gaps += `- **Rotation (${order.length}):** ${order.join(" → ")}\n`;
  if (optional.length) gaps += `- **Optional packages:** ${optional.join(", ")}\n`;
  if (absent.length) gaps += `- **Never had:**\n${absent.map((a) => `  - ${a}`).join("\n")}\n`;
  if (d.gaps?.length) {
    gaps += `\n**Outstanding work**\n\n${d.gaps.map((g) => `- ${g}`).join("\n")}\n`;
  } else {
    gaps += `\n_No outstanding gaps recorded._\n`;
  }
  gaps += `\n`;
}

await fsp.writeFile(path.join(ROOT, "docs/asset-gaps.md"), gaps);

fs.rmSync(outDir, { recursive: true, force: true });
console.log(`wrote docs/clip-wishlist.md (${missing.length} narrator/product gaps)`);
console.log(`wrote docs/asset-gaps.md (${m.DEVICES.length} machines)`);
